name: Mad_Lions
description: "Search Madrid Fountains."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: "^3.8.1"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  fluttertoast: ^8.2.12
  shared_preferences: ^2.2.2
  geolocator: ^14.0.1
  path_provider: ^2.0.9
  csv: ^6.0.0
  intl: ^0.20.2
  logger: ^2.2.0
  flutter_map: ^8.1.1
  latlong2: ^0.9.0
  firebase_core: ^3.14.0
  firebase_auth: ^5.6.0
  firebase_database: ^11.3.7
  cloud_firestore: ^5.6.9
  firebase_storage: ^12.4.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter_icons:
  android: true
  ios: true
  image_path: "assets/ic_app-playstore.png"

flutter:
  uses-material-design: true
  assets:
    - assets/ic_app-playstore.png
